export const Users = [
  {
    id: 1,
    profilePictures: "/assets/person/1.jpg",
    username: "Adesewa Adefalujo",
  },
  {
    id: 2,
    profilePictures: "/assets/person/2.jpg",
    username: "Ojo Johnson",
  },
  {
    id: 3,
    profilePictures: "./assets/person/3.jpg",
    username: "AraireOluwakiitan Ojo",
  },
  {
    id: 4,
    profilePictures: "./assets/person/4.jpg",
    username: "Dimple Adefalujo",
  },
  {
    id: 5,
    profilePictures: "./assets/person/5.jpg",
    username: "Zibah Adefalujo",
  },
  {
    id: 6,
    profilePictures: "./assets/person/6.jpg",
    username: "Funmilayo Adefalujo",
  },
  {
    id: 7,
    profilePictures: "./assets/person/7.jpg",
    username: "Abraham Adefalujo",
  },
  {
    id: 8,
    profilePictures: "./assets/person/8.jpg",
    username: "Treasure Ojo",
  },
  {
    id: 9,
    profilePictures: "./assets/person/9.jpg",
    username: "Wuraola Oluwalana",
  },
  {
    id: 10,
    profilePictures: "./assets/person/10.jpg",
    username: "Chloe Ojo",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/2.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    // desc: "Advertisement",
    photo: "/assets/post/1.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Be Happy Always!",
    photo: "/assets/post/3.jpg",
    date: "17 mins ago",
    userId: 3,
    like: 3,
    comment: 5,
  },
  {
    id: 4,
    desc: "Live it... Love it.",
    photo: "/assets/post/4.jpg",
    date: "10 mins ago",
    userId: 4,
    like: 8,
    comment: 7,
  },
  {
    id: 5,
    desc: "Let None Steal Your Joy",
    photo: "/assets/post/5.jpg",
    date: "50 mins ago",
    userId: 5,
    like: 6,
    comment: 8,
  },
  {
    id: 6,
    // desc: "",
    photo: "/assets/post/6.jpg",
    date: "35 mins ago",
    userId: 6,
    like: 9,
    comment: 24,
  },
  {
    id: 7,
    desc: "Trust Wisely",
    photo: "/assets/post/7.jpg",
    date: "34 mins ago",
    userId: 7,
    like: 8,
    comment: 7,
  },
  {
    id: 8,
    desc: "Live it... Love it.",
    photo: "/assets/post/8.jpg",
    date: "10 mins ago",
    userId: 8,
    like: 8,
    comment: 7,
  },
  {
    id: 9,
    desc: "Smile",
    photo: "/assets/post/9.jpg",
    date: "20 mins ago",
    userId: 9,
    like: 15,
    comment: 8,
  },
  {
    id: 10,
    desc: "All things bright and beautiful",
    photo: "/assets/post/10.jpg",
    date: "23 mins ago",
    userId: 10,
    like: 66,
    comment: 3,
  },
];
